language: go
go: 1.13
dist: bionic
sudo: required

branches:
  only:
  - master
  - develop

addons:
  apt:
    packages:
    - apt-transport-https
    - wget
    - git
    - openssh-server
    - tree
    - python3
    - python3-pip
    - python3-venv
    - fuse
    - attr

before_install:
  - sudo -H pip3 install setuptools
  - sudo -H pip3 install wheel
  - sudo -H pip3 install dxpy

env:
  global:
  - DX_APISERVER_HOST="stagingapi.dnanexus.com"
  - GOPATH="$HOME/go"

install:
# install golang system
- mkdir -p $GOPATH
- go get github.com/google/subcommands
- go get github.com/dnanexus/dxda
- go get github.com/jacobsa/fuse
- go get github.com/dnanexus/dxfuse
- go build -o $GOPATH/bin/dxfuse $GOPATH/src/github.com/dnanexus/dxfuse/cli/main.go

script:
# we need to login into dnanexus first
- dx login --staging --noprojects --token $DX_API_TOKEN

# sanity test for dxfuse, see that we can run it in a trivial
# way
- dxfuse=$GOPATH/bin/dxfuse
- $dxfuse --help

# run tests
- $GOPATH/src/github.com/dnanexus/dxfuse/test/local/local.sh
