language: go
sudo: true

go:
- 1.13.x

os:
#- linux
- osx

branches:
  only:
  - master
  - develop

env:
  global:
  # DX_API_TOKEN
  - secure: MeW7t4z5Q5ABp6W29iyRAo0ZWh9LU3IMZTkcqQ/xJubAxH8EZ7wvg1Rct4/3lx74WR2dsV2jh8F+23z8LAeKN85m3nEdGbmaWENwH+PQD6slcSR25NZQ1x7sHr8SGe26eRtPEptA22TyKm2mmiJg9Rs5FFl8+2Og+/FLdwczPdWqoZRGNC/yqsTg+6lc4oxal3SXtkHK9I2vJ3vqdB5WCzFEVAQv9FDcwPzJLSO/X18GSf8NQaimb23vYt9suCrYlZmQpCgja+Tnys3zpJxyy0qRV9wmwU7KauEupMNRvgn7iehhvUeWT9hEYUiOgtrw0mIkQa0wrnJIH4rD/SS5Wwh49BAkzl+HeDV8jtH2lQaBE1QxW1dcpwl6/+Wb0fHRgP1r0HOD0GSJ4lG40UC/uFseBi1FOUXqkWYC8BWmoXSyotkct1DgtQ8np0HrG7QHwsnt3XiySQZn0jT0ZSsYxvVdxyS9iDUxHC1fpac76jjzClYK3bnmmkZHh+8NaRr5RQti+vhHQbIZrXUOGBUGNstVaZOe8AQSVtbdTJnwkPukS2bxN2I6fx7uOReBmo1ncClLRx75bwv2Gqbe6ZRsm3LpIm3q/uanf6e8Bf1SXBt4ukjc3Bc4LgNqQhg7w59JCeTb2uWtyS9Xu1hcNSfB23kBAy1n2Gck4I6cFCrWnwA=
  - DX_APISERVER_HOST="stagingapi.dnanexus.com"
  - GOPATH="$HOME/go"

jobs:
  include:
    - os: linux
      dist: bionic

before_install:
# install the fuse filesystem for mac
-  if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -L -O https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.10.3/osxfuse-3.10.3.dmg; fi
-  if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo hdiutil attach osxfuse-3.10.3.dmg; fi
-  if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo installer -package /Volumes/FUSE\ for\ macOS/FUSE\ for\ macOS.pkg -target /; fi
-  if [ "$TRAVIS_OS_NAME" = "osx" ]; then ls -l /Library/Filesystems/osxfusefs.fs /usr/local/lib/libosxfuse*.dylib; fi

install:
# install golang system
- mkdir -p $GOPATH
- go get github.com/google/subcommands
- go get github.com/dnanexus/dxda
- go get github.com/jacobsa/fuse
- go get github.com/dnanexus/dxfuse
- GOOS=darwin go build -o $GOPATH/bin/dxfuse-$TRAVIS_OS_NAME $GOPATH/src/github.com/dnanexus/dxfuse/cli/main.go

script:
- dxfuse=$GOPATH/bin/dxfuse-$TRAVIS_OS_NAME
- "$dxfuse --help"

# make a mountpoint under the user's control
- mountpoint=$HOME/MNT
- mkdir -p $mountpoint

# start the filesystem
- sudo -E $dxfuse $mountpoint dxfuse_test_data &
- dxfuse_pid=$!
- sleep 2

# tests go here
- sudo ls -l $mountpoint
- ls -l $mountpoint

# export the dxfuse binary
- version=$($dxfuse --version)
- mkdir -p $mountpoint/dxfuse_test_data/releases/$version
- cp -f $dxfuse $mountpoint/dxfuse_test_data/releases/$version

# shutdown the filesystem, and ensure the file is uploaded
- sudo umount $mountpoint
- wait $dxfuse_pid
