language: go
sudo: false
dist: bionic

go:
- 1.13.x

os:
- linux
- osx

branches:
  only:
  - master
  - develop

env:
  global:
  # DX_API_TOKEN
  - secure: MeW7t4z5Q5ABp6W29iyRAo0ZWh9LU3IMZTkcqQ/xJubAxH8EZ7wvg1Rct4/3lx74WR2dsV2jh8F+23z8LAeKN85m3nEdGbmaWENwH+PQD6slcSR25NZQ1x7sHr8SGe26eRtPEptA22TyKm2mmiJg9Rs5FFl8+2Og+/FLdwczPdWqoZRGNC/yqsTg+6lc4oxal3SXtkHK9I2vJ3vqdB5WCzFEVAQv9FDcwPzJLSO/X18GSf8NQaimb23vYt9suCrYlZmQpCgja+Tnys3zpJxyy0qRV9wmwU7KauEupMNRvgn7iehhvUeWT9hEYUiOgtrw0mIkQa0wrnJIH4rD/SS5Wwh49BAkzl+HeDV8jtH2lQaBE1QxW1dcpwl6/+Wb0fHRgP1r0HOD0GSJ4lG40UC/uFseBi1FOUXqkWYC8BWmoXSyotkct1DgtQ8np0HrG7QHwsnt3XiySQZn0jT0ZSsYxvVdxyS9iDUxHC1fpac76jjzClYK3bnmmkZHh+8NaRr5RQti+vhHQbIZrXUOGBUGNstVaZOe8AQSVtbdTJnwkPukS2bxN2I6fx7uOReBmo1ncClLRx75bwv2Gqbe6ZRsm3LpIm3q/uanf6e8Bf1SXBt4ukjc3Bc4LgNqQhg7w59JCeTb2uWtyS9Xu1hcNSfB23kBAy1n2Gck4I6cFCrWnwA=
  - DX_APISERVER_HOST="stagingapi.dnanexus.com"
  - GOPATH="$HOME/go"

addons:
  apt:
    packages:
    - apt-transport-https
    - wget
    - git
    - tree

install:
- mkdir -p $GOPATH
- go get github.com/google/subcommands
- go get github.com/dnanexus/dxda
- go get github.com/jacobsa/fuse
- go get github.com/dnanexus/dxfuse
- go build -o $GOPATH/bin/dxfuse-$TRAVIS_OS_NAME $GOPATH/src/github.com/dnanexus/dxfuse/cli/main.go

script:
- dxfuse=$GOPATH/bin/dxfuse-$TRAVIS_OS_NAME
- "$dxfuse --help"
- mkdir /tmp/mount
- sudo $dxfuse /tmp/mount project-FbZ25gj04J9B8FJ3Gb5fVP41 &
- dxfuse_pid=$!
- sleep 2
- tree /tmp/mount
- version=$($dxfuse --version)
- mkdir /tmp/mount/dxfuse_test_data/releases/$version
- cp $dxfuse /tmp/mount/dxfuse_test_data/releases/$version
- sudo umount /tmp/mount
- wait $dxfuse_pid
