language: go
sudo: false
dist: bionic

go:
  - 1.13.x

# Start a build on for changes to master, or for pull requests
branches:
  only:
    - master
    - develop

env:
  global:
    # Set environment variables for Go
#    - PATH="/usr/local/go/bin:${PATH}"
    - GOPATH=/tmp/ci_tests/go

addons:
  apt:
    packages:
    - apt-transport-https
    - wget
    - git
    - tree

install:
  # Install Go packages
  - go get github.com/google/subcommands
  - go get golang.org/x/sync/semaphore
  - go install github.com/google/subcommands
  - go get github.com/dnanexus/dxda
  - go install github.com/dnanexus/dxda
  - go install github.com/dnanexus/dxda/cmd/dx-download-agent
  - go get bazil.org/fuse
  - go get golang.org/x/net/context
  - go get github.com/dnanexus/dxfuse
  - go install github.com/dnanexus/dxfuse

  - go build -o $GOPATH/bin/dxfuse $GOPATH/src/github.com/dnanexus/dxfuse/cmd/main.go