name : Build and upload release packages
on:
  release:
    types:
      - created

permissions:
  contents: write
  actions: write

jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build builder Docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          context: .
          file: builder.Dockerfile
          push: false
          tags: dxfuse-builder:latest
      - name: Build dxfuse
        run: |
          set -x
          docker run --rm \
            -v ${{ github.workspace }}:/dxfuse \
            -w /dxfuse \
            dxfuse-builder:latest \
            go build -o dxfuse-linux cli/main.go
      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: dxfuse-linux
          path: ./dxfuse-linux
      - name: Upload release asset
        uses: actions/upload-release-asset@64e5e85fc528f162d7ba7ce2d15a3bb67efb3d80 # v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dxfuse-linux
          asset_name: dxfuse-linux
          asset_content_type: binary/octet-stream
  macos:
    name: Macos build
    runs-on: macos-latest
    env:
        GOOS: darwin
        GOARCH: amd64
        CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: '1.22.6'
      - name: Build Macos executable
        run: |
          set -x
          go build -o dxfuse-macos cli/main.go
          chmod +x dxfuse-macos
      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: dxfuse-macos
          path: ./dxfuse-macos
      - name: Upload release asset
        uses: actions/upload-release-asset@64e5e85fc528f162d7ba7ce2d15a3bb67efb3d80 # v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dxfuse-macos
          asset_name: dxfuse-macos
          asset_content_type: binary/octet-stream
