name : Tests
on:
  push:
    branches:
      - master
      - github_cicd
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build and test linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.2'

      - name: Install & build
        run: |
          set -x
          pwd
          sudo apt-get update
          sudo apt-get install -y apt-utils make \
          wget git build-essential apt-transport-https \
          openssl libssl-dev zip unzip libffi-dev \
          python python-pip python-dev

          # Install printing with colors python package
          pip install setuptools wheel
          wget https://raw.githubusercontent.com/dnanexus/dx-toolkit/master/src/python/requirements.txt
          pip install -r requirements.txt

          # I used python2 because this installing dxpy causes a segmentation fault on pip3.
          # I have no idea why.
          pip install dxpy

          go build -o dxfuse cli/main.go

      - name: Login to dnanexus
        env:
          DX_TOKEN : ${{ secrets.DX_TOKEN }}
        run: |
          # The CLI binaries are installed in .local
          export PATH="$PATH:$HOME/.local/bin"
          dx login --staging --token $DX_TOKEN --noprojects
          dx select dxfuse_test_data

      - name: Run the tests
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          ./scripts/run_tests.py --test correct --size large
  macos:
    name: Macos build
    runs-on: macos-10.15
    env:
        GOOS: darwin
        GOARCH: amd64
        CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.2'
      - name: Install & build
        run: |
          set -x
          go build -o dxfuse-macos cli/main.go