name : Tests
on:
  push:
    branches:
      - master
      - github_cicd
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  applet-test:
    name: Applet dxfuse tests
    needs: local-test
    runs-on: ubuntu-20.04
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.6'

      - name: Install & build
        run: |
          set -x
          pwd
          sudo apt-get update
          sudo apt-get install -y apt-utils make \
          wget git build-essential apt-transport-https \
          openssl libssl-dev zip unzip libffi-dev \
          python3 python3-pip python3-dev

          # Install printing with colors python package
          python3 -m pip install --upgrade setuptools wheel pyOpenSSL
          wget https://raw.githubusercontent.com/dnanexus/dx-toolkit/master/src/python/requirements.txt
          python3 -m pip install -r requirements.txt

          python3 -m pip install dxpy

          go build -o dxfuse cli/main.go

      - name: Applet dxfuse tests
        env:
          DX_TOKEN : ${{ secrets.DX_TOKEN }}
        run: |
          # The CLI binaries are installed in .local
          export PATH="$PATH:$HOME/.local/bin"
          dx login --staging --token $DX_TOKEN --noprojects
          dx select dxfuse_test_data
          # Build test applets with new dxfuse executable
          make -C ./test aws
          # Run correctness tests
          ./scripts/run_tests.py --test correct --size large --verbose

  local-test:
    name: Local dxfuse tests
    runs-on: ubuntu-20.04
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.6'

      - name: Install & build
        run: |
          set -x
          pwd
          sudo apt-get update
          sudo apt-get install -y apt-utils xattr attr make \
          wget git build-essential apt-transport-https \
          openssl libssl-dev zip unzip libffi-dev \
          python3 python3-pip python3-dev
          # Install printing with colors python package
          python3 -m pip install --upgrade setuptools wheel pyOpenSSL
          wget https://raw.githubusercontent.com/dnanexus/dx-toolkit/master/src/python/requirements.txt
          python3 -m pip install -r requirements.txt

          python3 -m pip install dxpy

          go build -o dxfuse cli/main.go

      - name: Local dxfuse tests
        env:
          DX_TOKEN : ${{ secrets.DX_TOKEN }}
        run: |
          # The CLI binaries are installed in .local
          export PATH="$PATH:$HOME/.local/bin"
          dx login --staging --token $DX_TOKEN --noprojects
          dx select dxfuse_test_data
          # Run correctness tests
          sudo PATH=$PATH -E ./scripts/run_tests.py --test local

  macos:
    name: Macos build
    runs-on: macos-latest
    env:
        GOOS: darwin
        GOARCH: amd64
        CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.6'
      - name: Install & build
        run: |
          set -x
          go build -o dxfuse-macos cli/main.go
